//------------------------------------------------------------------------------
// <auto-generated>
//     此代码由工具生成。
//     对此文件的更改可能会导致不正确的行为，并且如果
//     重新生成代码，这些更改将会丢失。

using System;

namespace Quick.Domain
{
	/// <summary>
    /// 仓储操作层接口 —— Role
    /// </summary>
    public interface IRoleRepository : IRepository<Role>
    {
    }
}
